// <auto-generated />
using AutomationTravelAgency.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomationTravelAgency.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AutomationTravelAgency.Data.Entity.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FarePerKm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("int");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DriverId = "1023",
                            FarePerKm = "$0.75",
                            SeatingCapacity = 7,
                            VehicleName = "Traveler's Van",
                            VehicleNo = "AB 12 CD 3456",
                            VehicleType = "Van"
                        },
                        new
                        {
                            Id = 2,
                            DriverId = "2045",
                            FarePerKm = "$1.00",
                            SeatingCapacity = 5,
                            VehicleName = "Explorer SUV",
                            VehicleNo = "XY 45 EF 6789",
                            VehicleType = "SUV"
                        },
                        new
                        {
                            Id = 3,
                            DriverId = "3456",
                            FarePerKm = "$0.50",
                            SeatingCapacity = 50,
                            VehicleName = "Comfort Coach",
                            VehicleNo = "GH 78 IJ 1234",
                            VehicleType = "Bus"
                        },
                        new
                        {
                            Id = 4,
                            DriverId = "4567",
                            FarePerKm = "$0.60",
                            SeatingCapacity = 15,
                            VehicleName = "Journey Shuttle",
                            VehicleNo = "KL 90 MN 5678",
                            VehicleType = "Minibus"
                        },
                        new
                        {
                            Id = 5,
                            DriverId = "5678",
                            FarePerKm = "$0.80",
                            SeatingCapacity = 8,
                            VehicleName = "Adventure Wagon",
                            VehicleNo = "OP 34 QR 9101",
                            VehicleType = "SUV"
                        },
                        new
                        {
                            Id = 6,
                            DriverId = "6789",
                            FarePerKm = "$0.90",
                            SeatingCapacity = 4,
                            VehicleName = "Nomad Ride",
                            VehicleNo = "ST 56 UV 1213",
                            VehicleType = "Sedan"
                        },
                        new
                        {
                            Id = 7,
                            DriverId = "7890",
                            FarePerKm = "$0.45",
                            SeatingCapacity = 40,
                            VehicleName = "Expedition Bus",
                            VehicleNo = "WX 78 YZ 1415",
                            VehicleType = "Coach"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
